purescript/trypurescript

- js/index.js
Just a suggestion. You used two spaces in all the examples, as far as I can see.
> Use two spaces for tabs in the editor.

- css/index.css
- index.html
- js/index.js
Adds a 'Share' button at the top right of the screen.
Pressing on it will trigger a confirm message. after that it will:
- Create an annonymous gist via github
- Refresh the page with the `gist` query parameter updated to the newly created gist
or it will fail and `alert` the user and will print the response object in console.
A few more changes:
- Tooltips for buttons
- pointer cursor for buttons
- Don't load session if `gist` query parameter is present (does that make sense?)
[Viewable here](https://soupi.github.io/trypurescript).
> Adding a button to publish code as an annonymous gist

- css/slides.css
- index.html
- js/index.js
This depends on a backend for `purescript-slides` at endpoint `https://compile.purescript.org/slides` (can be changed of course) that has packages as suggested in [this bower.json](https://gist.github.com/soupi/aec3c558ac1fedce6c4b2e740dc3e9e0).
[Preview](https://soupi.github.io/trypurescript) will not work until we have a backend of course :)
> Adding slides as a possible backend

- css/slides.css
Should fix image size problems is try-purescript (especially on mobile)
- [Current try-purs preview](http://try.purescript.org/?gist=639c65f69c38b043dabf29f27266bfe9&backend=slides&view=output)
- [After fix preview](https://soupi.github.io/trypurescript/?gist=639c65f69c38b043dabf29f27266bfe9&backend=slides&view=output)
if you don't see the difference try to shrink your window.
> img max-width for slides.css

- server/Main.hs
- stack.yaml
- trypurescript.cabal
This is a work-in-progress.
The idea is to expose a `/search` endpoint which Pursuit can use to implement type search using the externs held by the Try PureScript process.
I added this here instead of in a separate service since we already have the data in memory, and it seems wasteful to load it all twice on the server when we have limited resources.
The main issue is that replacing type variables with unknowns generally yields too many results. We could use skolems instead, which works better in some cases, but in other cases it gives too few results, since the generalization step doesn't work in the solver.
Another thing I would like to try is to resolve unqualified constructors by looking up any matching constructors in the `Environment`.
> Type search

- js/index.js
In the previous fix of `.load()` -> `.ready()` it appear that now `iframe` is `ready` before body is ready. this is ok for most cases but not for mathbox which has an extra js dep. and at the point of `var body` the `iframe` is not ready yet.
This fixes this issue by busy waiting on `body` to be ready. It's a bit ugly, but i haven't found a better solution from googling this issue.
> busy wait on body for iframe to load

- server/Main.hs
- stack.yaml
- staging/core/psc-package.json
- trypurescript.cabal
My plan is to deploy this over the weekend. I will start by disabling all "Try X" services, and I'll turn them back on as soon as the necessary libraries are updated and I have a working `psc-package.json` or `bower.json` for each one.
So there's no real rush, since the core "Try PureScript" will be working, but the other services will be offline initially.
cc @sharkdp @soupi @rintcius
> Updates for 0.11

- css/index.css
- index.html
- js/index.js
This commit adds a link to a gist on github (useful for mobile users who just want to read the code) as suggested [here](https://twitter.com/bkase_/status/879030876377665536).
- When a link to gist is available it will add a 'Gist' link under 'View Mode' menu ([Preview](https://soupi.github.io/trypurescript/))
- When  a gist is not available it will not show this option at all ([Preview](https://soupi.github.io/trypurescript/?gist=3f735aa2a652af592101))
> adding a link to gist under view mode

- server/Main.hs
Includes warnings in the API, so that we can show them in the gutter area.
> Return warnings from API

- js/index.js
- src/Try/QueryString.purs
`union` is left-biased: https://pursuit.purescript.org/packages/purescript-maps/3.5.0/docs/Data.StrMap#v:union
This should fix the issue where saving a gist would not update the url if the url already had a gist parameter. But I haven't tested it 😁
> setQueryStrings should replace existing parameters

- client/frame.html
- client/index.html
- client/js/frame.js
- client/package.json
- client/src/Main.purs
- client/src/Try/API.purs
- client/src/Try/Config.purs
- client/src/Try/Loader.purs
- client/src/Try/Session.purs
- client/src/Try/Shim.purs
- client/src/Try/Types.purs
I merged the changes from #128 into master and updated `Try.Config.mainGist` to point to my updated fork.
In order to load the modules, it's necessary to copy the contents of `staging/core/.psci_modules/node_modules/` into `client/js/output/`.
@hdgarrood Again this is the bare minimum. The other backends haven't been removed, no READMEs have been updated, and none of the comments from https://github.com/purescript/trypurescript/pull/135#pullrequestreview-363054421 have been implemented.
@natefaubion your changes are great! This will likely allow a lot of flexibility for people wanting to run TryPS locally.
> Merge changes from #128

- deploy/remote.sh
- deploy/run.sh
Based on the Pursuit one. I've used this to deploy to 159.65.220.76, which will be the new try.purescript.org box. It doesn't quite work yet because a) the development config is compiled in to the client bundle right now, which means that it tries to hit `localhost:8081` for compiling, and b) nginx is not yet configured to server the output directory, but I can fix these things separately.
> Add deploy script

- trypurescript.cabal
-threaded is probably a good idea even if we aren't using multiple
cores, because it allows using OS threading, which I think should be
able to leverage the OS to interleave work more efficiently,
particularly for FFI calls. It also means that if we want to deploy the
compile server on a box with more cores, that's easy to do, we just
tweak the RTS configuration. See
<https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/phases.html?highlight=threaded#ghc-flag--threaded>
Being able to tweak the RTS options (enabled by -rtsopts) has been
absolutely essential for getting Pursuit to run reliably and to keep
memory usage under control, so I'm sure we will want it here too.
> Enable -threaded and -rtsopts for compile server

- ci/build.sh
- client/package.json
Right now we are still building the dev config into the deploy bundles,
because I got the config overriding wrong. I've actually tested this
version, at least. See https://docs.npmjs.com/files/package.json#config
> Fix usage of production config in CI

- README.md
* The Try PureScript client no longer uses a bundle of preloaded
modules; fix a sentence which says it does
* Document that the request body must be a module called Main
* Document the formats of the various JSON responses in more detail
* Document the fact that we now expose the output directory from
compile.purescript.org
> Update readme: server API

- server/Main.hs
- stack.yaml
- stack.yaml.lock
- trypurescript.cabal
I don't think there are any changes in 0.13.8 which are visible externally, but the CBOR externs change does noticeably affect startup time, which is nice.
> Update to v0.13.8

- server/Main.hs
- trypurescript.cabal
> Only listen on 127.0.0.1

- deploy/nginx.conf
Amends the nginx config so that nginx will respond to HTTP requests
whose path starts with /.well-known/ with the matching file in
/var/www/letsencrypt-webroot, if any. This allows Let's Encrypt to
verify domain ownership in order to renew certificates automatically.
The `certbot` program is configured by default to renew all certificates
once they are approaching their expiration dates, so with these changes,
all that needs to happen on the server to enable subsequent renewals to
be handled completely automatically is:
- Certbot needs to be told to use the "webroot" plugin for domain
verification with the appropriate directory when renewing certificates
- Nginx needs to be set up to reload its configuration periodically so
that newly renewed certificates are picked up.
Note that certbot …
> Enable automated SSL certificate renewal

- staging/src/TryPureScript.js
- staging/src/TryPureScript.purs
Unless I'm missing some crucial context, there doesn't seem to be a reason why we need to use the FFI for `encode`.
Resolves #185.
> Implement `encode` in PureScript

- client/public/index.html
Currently, the affjax example in Halogen does not work and returns the following response:
```
Blocked form submission to '' because the form's frame is sandboxed and the 'allow-forms' permission is not set.
```
I believe this fixes the issue, although I haven't tested it yet. Thanks!
> Updates trypurescript to work with Halogen Affjax example

- server/Main.hs
I finally got Try PureScript building on my machine and took some time to review the server code. While there, I noticed that there are a number of unused language pragmas, imports, and definitions in the file. This PR simply removes the dead code from the file (and removes one unnecessary dollar sign).
> Remove unused pragmas, imports, and definitions

- client/.travis.yml
- client/package.json
- client/spago.dhall
- client/test/Fixture.purs
- client/test/Fixture/compile-failure.json
- client/test/Fixture/compile-other-error.json
- client/test/Fixture/compile-success.json
- client/test/Main.purs
The PureScript 0.14 release helped drive the point home, for me, that core libraries and infrastructure ought to use core libraries (or contrib, or node, etc.) wherever possible.
As part of the updates originally outlined in #199 I thought we could switch to use `argonaut` rather than `foreign-generic` for the API in Try PureScript. We already depend on `argonaut` and are receiving its `Json` type via Affjax, so it feels like a more natural fit than `foreign-generic` in addition to being a contrib library.
This PR takes a first step by adding API response fixtures and tests for the existing `foreign-generic` implementation. This helps ensure that switching to a new library will still decode correctly without having to test manually.
> Add fixtures for API responses

- client/package.json
The `config` key is no longer necessary in the `package.json` file because we've hardcoded the config paths into the scripts.
> Remove config key from package.json

- client/src/Try/API.purs
This fixes the CORS issue also noticed in #215, but we can merge this until folks have time to review that pull request.
> Use string body instead of Json in compile request

- README.md
> Update local compile server setup instructions so that code compiles

- server/Main.hs
Closes #222. When implementing #209 I accidentally provided an empty array to `rebuildModule` for the externs; this fix properly threads the externs through. As @JordanMartinez noticed in #222 we also can remove the `initNamesEnv` argument as it is no longer used.
Evidence that things work once again:
> Provide externs to rebuildModule

- .gitignore
- README.md
I was getting a 500 error in [#225 (comment)](https://github.com/purescript/trypurescript/pull/225#issuecomment-850724476) because the symbolic link created via `ln -s output ../client/public/js/output` was broken. 
Adding the `--relative` flag fixes the issue for me. I get the same view Thomas did in #225.
> Create valid symbolic link to output dir

- server/Main.hs
> Set buffering to LineBuffering to stop mangled 'Compiline ModName' text

- .github/PULL_REQUEST_TEMPLATE.md
- CHANGELOG.md
We don't currently have a changelog in this repo. Let's make things easier on ourselves. This was copy-pasted from the `purescript` repo. I'm guessing we don't need a 'CONTRIBUTORS.md' file?
---
**Checklist:**
> Generate changelog; add PR template

- .github/workflows/ci.yml
- deploy/start
- Fix deploys by using an absolute directory for XDG_CACHE_HOME
- Pin CI to Ubuntu 20.04, and add note that this must be kept in sync
with the server
This probably doesn't need to go in the changelog
---
**Checklist:**
> Deployment fixes

- README.md
The README is still pointing at the Travis build status, but it should be pointing to the GitHub Actions CI workflow instead. (I think this can be left out of the CHANGELOG.)
> Fix status badge in README

- .github/workflows/ci.yml
I noticed that caching doesn't appear to be working properly and is using the stack.yaml instead of stack.yaml.lock file. This PR updates the method.
> Update caching for dependencies in CI

- CHANGELOG.md
- client/src/Try/Loader.purs
Importing from `React.Basic.Hooks` is broken (see #236).
This seems to be because the `requireRegex` used by `parseDeps` only parses required modules using the `var` keyword, while recent updates to `React.Basic` modules switched from [`var` to `const`](https://github.com/lumihq/purescript-react-basic/commit/3e00fc48f5a0cab48f82f44296727902d54f6443#diff-700cdb9d6a9308b6f0d2162dde1ca07cd1c5c5fb9fa6344a4c4beaae92a69d0c).
This PR updates the `requireRegex` to match on
```js
const React = require("react")
```
in addition to the existing supported format
```js
var React = require("react")
```
<details><summary><strong>Before</strong></summary>
Note that the React "shim" (from `https://unpkg.com/react@16.13.1/umd/react.development.js`) is not included in *Sources* …
> Add const to requireRegex

- CHANGELOG.md
- README.md
- stack.yaml
- stack.yaml.lock
This PR updates Try PureScript to use the 0.14.3 compiler. I opted to update Try PureScript quickly because of issues like https://github.com/purescript/purescript/issues/4110, which are present on current Try PureScript:
...but not in this PR:
This PR uses the same commit for PureScript as https://github.com/purescript/pursuit/pull/436.
---
**Checklist:**
- ~Updated or added relevant documentation~
- ~Added a test for the contribution (if applicable)~
> Update to use PureScript 0.14.3

- CHANGELOG.md
- staging/src/TryPureScript.purs
Fixes `"text try.purescript.org?github=/<owner>/<repo>/<branch or tag>/<file>.purs"` being shown as `try.purescript.org?github=/<owner>///.purs` in the main example
---
**Checklist:**
> Fix encode only replacing first occurrences

- CHANGELOG.md
- client/public/index.html
- client/src/Try/Container.purs
Keeps the loader up longer, lowering blank-screen time to less than 50ms.
---
**Checklist:**
> Adds longer loading screen

- README.md
- RELEASE.md
Addresses part of #219.
---
**Checklist:**
> Add release docs

- CHANGELOG.md
Finalizes changelog for a new release, `v2021-11-30.1`, so we can redeploy with #261 included.
> Finalize changelog for next release: v2021-11-30.1

- CHANGELOG.md
- client/public/css/index.css
- client/src/Try/Container.purs
- client/src/Try/Loader.purs
Fixes https://github.com/purescript/trypurescript/issues/265
These are minimal changes to render an error message in the case of a missing FFI dependency. We are displaying the message in the right pane (using the same `renderPlainText` function that's used for displaying the JS output for example) as well as throwing an error so that it's visible in the browser console. If there are multiple missing dependencies, only the first will be rendered to the user.
I looked into accumulating an array of misses using `Data.Validation.Semigroup` in https://github.com/purescript/trypurescript/pull/267, but I don't know that the added complexity was justified, since it seems like there would rarely be more than a single missing FFI dep.
<details><summary><strong>Single …
> Display FFI errors to user

- CHANGELOG.md
- client/public/frame.html
Currently, try.purescript.org will run the `main` function twice when one uses `TP.render =<< TP.withConsole <<< log "foo"`
Updating `es-module-shims` to the next version fixes this on Firefox  when I test the client against the production server.
---
**Checklist:**
> Fix double main call by updating es-module-shims to 1.5.6

- .github/workflows/ci.yml
- CHANGELOG.md
- RELEASE.md
- client/package.json
- client/public/css/index.css
- client/src/Try/Container.purs
- client/src/Try/SharedConfig.purs
- client/updateSharedConfigVersions.mjs
Fixes #149. Screenshots below. CI tests (in progress) should prove that checks work:
Normal view:
Mobile view:
---
**Checklist:**
> Add PureScript & Package Set version info

- CHANGELOG.md
- client/examples/ADTs.purs
- client/examples/DoNotation.purs
- client/examples/Generic.purs
- client/examples/Loops.purs
- client/examples/Operators.purs
- client/examples/QuickCheck.purs
- client/examples/Records.purs
- client/examples/Recursion.purs
- client/examples/TypeClasses.purs
- client/public/frame.html
Fixes #283. Also allows updates the `frame.html` file to include a `<div id="root"></div>`. See https://github.com/JordanMartinez/purescript-cookbook/issues/198
---
**Checklist:**
> Use div-root; fix examples' warnings

- CHANGELOG.md
- client/package.json
Fixes #284 
---
**Checklist:**
> Drop extra 'main();' call when bundling

- CHANGELOG.md
- RELEASE.md
- client/public/frame.html
Fixes #289. However, trying to run the React examples from the cookbook get a weird error even with this fix:
- Works: [`HelloReactHooks`](https://github.com/JordanMartinez/purescript-cookbook/blob/master/recipes/HelloReactHooks/src/Main.purs)
- Fails: [`ButtonsReactHooks`](https://github.com/JordanMartinez/purescript-cookbook/blob/master/recipes/ButtonsReactHooks/src/Main.purs)
---
**Checklist:**
> Fix NPM shim resolver on Firefox

- CHANGELOG.md
- client/public/frame.html
Fixes #293.
---
**Checklist:**
> Fix double main invocation using shim mode

- CHANGELOG.md
- client/src/Try/Container.purs
I noticed that using the `view=output&js=true` query params (e.g. https://try.purescript.org/?view=output&js=true) don't show the compiled JavaScript but rather shows a loading screen for forever. This is annoying because I can't just show others what PureScript's output looks like when they're curious. 
This fixes that.
---
**Checklist:**
> Show compiled JS based on query params only

- CHANGELOG.md
- client/public/frame.html
Version 1.5.12 is currently - including the latest bug fix 1.5.15 - the best version for the project where the examples work in all tested browsers.
See these discussions for more details:
* <https://github.com/purescript/trypurescript/pull/297#issuecomment-1214194277>
* <https://github.com/guybedford/es-module-shims/issues/324#issuecomment-1214452714>
> es-module-shims 1.5.12

- CHANGELOG.md
- client/examples/Main.purs
Now that #299 has landed, we ought to update the main example so that it makes it clear that code can be shared via the URL alone.
---
**Checklist:**
- ~~Linked any existing issues or proposals that this pull request should close~~
- ~~Updated or added relevant documentation~~
- ~~Added a test for the contribution (if applicable)~~
> Update main example to note the URL contains code

- CHANGELOG.md
The changelog referenced #306 as the PR for updating to 0.15.10, but it was actually #310.
> Fix PR reference in changelog
