examples/ffi.purs
=> Fix ffi example.

css/index.css, js/index.js
It appears that `innerText` is not supported in these browsers.
However `appendChild` and `createTextNode` appear to have better support: http://caniuse.com/#search=createTextNode
=> Bug fixes - no output in Firefox/Safari & crazy scroll bars

css/index.css
Also looks fine with Edge in IE 10 rendering mode.
=> Fix for rendering issues in IE Edge

js/index.js
Should close #12 
The idea here is to have a session per tab running updating the localSorage to preserve the code in case of reload or browser crash.
=> Save code buffer

README.md, css/index.css, index.html
This time the help button is on the top right. Will it go through? ☺
=> adding a readme and a help button linking to it

css/flare.css, index.html, js/index.js
I have adapted my old Try Flare client code to the new interface with just two panes. Thanks again for updating the backend!
=> Add client code for try-flare.

css/flare.css
=> Increase label width and fix Firefox invisible slider

js/index.js
[Preview](http://soupi.github.io/trypurescript) if there's a need for that :)
=> adding meta viewport tag and fixing backend&core in startSlides

js/index.js
[Preview](https://soupi.github.io/trypurescript) as usual.
=> meta content tag and image from imgur over https

css/index.css, index.html, js/index.js
This adds a red underline to the text where the error occurred.
Fixes #33.
=> JSON errors

js/index.js
This fixes:
1. Github's unicorn error when trying to "show js" or press the compile button
2. Fix cache string - will now try to use the cache string to load previously cached code and backend settings
Changes can be viewed [here](https://soupi.github.io/trypurescript).
=> Fix github unicorn error and cache

js/index.js
Reverts purescript/trypurescript#65
=> Revert "Fix github unicorn error and cache"

js/index.js
This should fix #66 That was introduced in #65 for chromium browser
Please check that it works [here](http://soupi.github.io/trypurescript) and tell me if it isn't.
Thanks
=> Fixing PR #66

js/index.js
=> Escape HTML in Show JS output

css/slides.css
- [before](http://try.purescript.org/?backend=slides) (go to 2nd slide)
- [after](http://soupi.github.io/trypurescript/?backend=slides) (go to 2nd slide)
Thanks
=> Updating slides css for code elements

src/Main.purs
Fixes a bug found by @joneshf when position info is missing.
=> Fix missing errors

staging/flare/psc-package.json
Fixes #103 . Should be merged at the same time as #107 (also see #106).
- I checked that all Gist code examples still work, except for the FlareCheck=>Sparkle renaming, which I already fixed.
/CC @joneshf
=> Add try-flare backend

index.html
As mentioned in the fpchat Slack channel this PR removes the "Share" button pending resolution of #118.
=> Comment out "Share" button until #118 is resolved

client/src/Try/Shim.purs, staging/core/psc-package.json
With a few additions to the psc-package.json file I was able to get a
page using purescript-react working. I saved the gist here:
https://gist.github.com/hdgarrood/828a40781d155fe74d91f1332ceaa922
=> Update shim versions

server/Main.hs
This requires the server to keep a giant JS bundle in memory, and it's
no longer necessary since individual modules are now loaded on demand.
=> Remove the /bundle endpoint

deploy/nginx.conf
We need these to be able to read the response from the client using xhr
=> Add CORS headers for output directory

trypurescript.cabal
=> [#169] Do away with version numbers

CHANGELOG.md, server/Main.hs, stack.yaml
Updates the server to use `v0.14.2`. Also speeds up the server slightly by using `rebuildModule'`
---
**Checklist:**
=> Update to v0.14.2

CHANGELOG.md, stack.yaml
=> Update to v0.14.4 PS release

CHANGELOG.md, staging/src/TryPureScript.purs
I, uh, didn't test this. Let me know if that's a problem.
---
**Checklist:**
=> Fix double-encoding of quotation marks

CHANGELOG.md, client/examples/ADTs.purs, client/examples/DoNotation.purs, client/examples/Generic.purs, client/examples/Loops.purs, client/examples/Operators.purs, client/examples/QuickCheck.purs, client/examples/Records.purs, client/examples/Recursion.purs, client/examples/TypeClasses.purs
Fixes #291 
---
**Checklist:**
=> Add Effect import to examples
